---
- hosts: all
  become: yes
  tasks:
    - name: update apt cache
      apt:
        update_cache: yes

    - name: delete nginx server
      apt:
        name: nginx
        state: absent

    - name: delete index.html from web server directory
      file:
        path: /var/www/html/index.html
        state: absent
        owner: www-data
        group: www-data
        mode: '0644'   


