---

- name: update cache (ubuntu)
  tags: always
  apt:
    update_cache: yes
  when: ansible_distribution == "Ubuntu"

- name: update cache (RedHat)
  tags: always
  dnf:
    update_cache: yes
  when: ansible_distribution == "RedHat"



- name: include ubuntu tasks
  include_tasks: ubuntu.yml
  when: ansible_distribution == "Ubuntu"

- name: include redhat tasks
  include_tasks: redhate.yml
  when: ansible_distribution == "RedHat"


- name: copy file to ubuntu server
  include_tasks: copy-file.yml 
  when: ansible_distribution == "Ubuntu"        